### ISSUE TITLE
Add typescript.definition entry in package.json for tsd

### ISSUE THREAD

**Issue by cybrown** [rbuckton/ReflectDecorators#10]
Tsd supports definition files in external modules, but it needs to be in the "typescript" section of the package.json file.

Currently, this information is in the typings entry, and does not work out of the box with tsd.

**Comment by maxleiko** [comment]
Upvoting this :+1:

Much needed for `tsd link` [doc](https://github.com/DefinitelyTyped/tsd#link-to-bundled-definitions)

**Comment by rbuckton** [comment]
Closed #10 via #11.
