### ISSUE TITLE
Build failing when applied to class

### ISSUE THREAD

**Issue by oriches** [rbuckton/ReflectDecorators#13]
I'm trying to apply metadata to an exported class and I'm getting the following build error in Visual Studio 2013, I can apply metadata to method fine.

require("../libs/reflect-metadata/Reflect");

@Reflect.metadata("ExampleKey", "ExampleValue")
export class ExampleClass {    
}

Gives the following build error, any ideas what I'm doing wrong?

Error	1	Type '(<TFunction extends Function>(target: TFunction) => void | TFunction) | (<T>(target: Object, prop...' is not assignable to type '(target: typeof ExampleClass) => void | typeof ExampleClass'.
  Type '<T>(target: Object, propertyKey: string | symbol, descriptor: TypedPropertyDescriptor<T>) => void...' is not assignable to type '(target: typeof ExampleClass) => void | typeof ExampleClass'.	C:\XXXX.ts	5	1	XXXX.Server

**Comment by oriches** [comment]
Also, it is working when I apply it imperatively:

constructor() {
        super();

        Reflect.defineMetadata("Key1", "Value1", this);
    }

**Comment by rbuckton** [comment]
I'll take a look at the typings for the library and see if I can determine what needs to change.
