### ISSUE TITLE
Does not work in Ie8 

### ISSUE THREAD

**Issue by Alexandr-Ilyin** [rbuckton/ReflectDecorators#19]
It seems like getters and setters are used for Map and Set classes , so it does not work in ie8

**Comment by rbuckton** [comment]
reflect-metadata requires a number of ES5 features to work properly, including `Object.getPrototypeOf`. The only way to implement a consistent `Object.getPrototypeOf` in ES3 requires mutating the object which could have unintentional side effects (such as changing the insertion order for `for..in` enumeration).

For this reason, I'm closing this task. If you feel this was closed in error, please reopen with comments.
