### ISSUE TITLE
Initial Release

### ISSUE THREAD

**Issue by EisenbergEffect** [rbuckton/ReflectDecorators#2]
We've got our own metadata system in Aurelia, but this would work fine for us. Since we are working towards a standard, I would like to convert Aurelia over to use this library internally. To feel good about doing that, I would need at least a 0.1.0 release so that I can properly import it via jspm and/or bower. Any chance you could do this? If you can follow semver, then we can manage Aurelia's use of this library well and would be happy with it. This would also enable us to automatically enable our DI to work with TS type info.

**Comment by rbuckton** [comment]
I have no problem with bumping the minor version, as it has reached a point where it is stable enough for broader testing and adoption.

**Comment by rbuckton** [comment]
@EisenbergEffect I added a suite of tests to verify conformance to spec behavior and have bumped the version to "0.1.0".
