### ISSUE TITLE
Provide the ability to enumerate metadata on all property keys

### ISSUE THREAD

**Issue by billccn** [rbuckton/ReflectDecorators#20]
The current proposed metadata API provides no ways of enumerating all the decorated property keys. This information should be available "statically" without a fully instantiated object.

For example, say I have a decorator that sets default values for each decorated property during construction. As the properties would otherwise have never been assigned to, `Object.keys` returns nothing but the `Reflect` object clearly knows which properties have decorators.

**Comment by JohnWhiteTB** [comment]
As a workaround, I can recommend using a PropertyDescriptor on the prototype (or the constructor function itself for static properties):

```typescript
function InitProperty(target: any, propertyKey: string | symbol) {
    // Set initial value, this could come through a decorator factory.
    var initialValue = 0;

    Object.defineProperty(target, propertyKey.toString(), {
        set: function (value) {
            this["__" + propertyKey.toString()] = value;
        },
        get: function () {
            return this["__" + propertyKey.toString()];
        }
    });
}
```

**Comment by rbuckton** [comment]
Please also consider [this workaround](https://github.com/rbuckton/ReflectDecorators/issues/35#issuecomment-238708774).

I don't plan to make any further changes to the public API for this project as the official proposal for decorators is undergoing changes as part of the standardization process that will ultimately affect this project.
