### ISSUE TITLE
typing definitions should have .d.ts suffix

### ISSUE THREAD

**Issue by rolandjitsu** [rbuckton/ReflectDecorators#23]
It looks like the typing definitions for `Reflect.js` are `Reflect.ts`, but should that not be `Reflect.d.ts`?

**Comment by onreachable** [comment]
Actually it is [reflect-metadata.d.ts](https://github.com/rbuckton/ReflectDecorators/blob/master/reflect-metadata.d.ts)

**Comment by rolandjitsu** [comment]
Ok, the problem is that I am using jspm and plugin-typescript, and plugin typescript does not pickup on the typings. So I need to add an override as such:
```js
"npm:reflect-metadata@0.1.3": {
       "meta": {
                    "Reflect.js": {
                        "typings": "Reflect.ts"
                    }
                }
            }
```
If there would be a `Reflect.d.ts`, the the plugin would be able to automatically load the type definitions.

**Comment by onreachable** [comment]
Changing it to:
```
"npm:reflect-metadata@0.1.3": {
       "meta": {
                    "Reflect.js": {
                        "typings": "reflect-metadata.d.ts"
                    }
                }
            }
```
doesn't work as well?

**Comment by rolandjitsu** [comment]
@onreachable I will try it tomorrow morning and let you know.

**Comment by rolandjitsu** [comment]
I think that works as well. But it would be nice not to have to write any overrides at all, that is why I mentioned having `Reflect.d.ts`, because JSPM actually loads that file and not a `reflect-metadata.js`. If it would load the `reflect-metadata.js`, then there would be no problem as it would load the `reflect-metadata.d.ts` typings.

**Comment by onreachable** [comment]
Yeah, but I believe that this project isn't maintained anymore, since this proposal was been accepted and will be implemented soon in typescript/ES7 ...

**Comment by rolandjitsu** [comment]
Ok, but it's still widely used, so it may be worth fixing this until the proposal is implemented.

**Comment by onreachable** [comment]
@rbuckton This API was already incorporated in typescript somehow?!

**Comment by rbuckton** [comment]
@onreachable No, TypeScript does not incorporate this API. Metadata (and how it applies to decorators) is currently under consideration by the TC39 decorators champion. This library is still maintained, but has had minimal changes recently as we have been discussing how this will move forward.

**Comment by rolandjitsu** [comment]
I have discovered that not having `Reflect.ts` as `Reflect.d.ts` causes more problems when I use karma-browserify and tsify.

Also, that file actually contains definitions only, so it should theoretically have the `.d.ts` extension. Moreover, the typings from `reflect-metadata.d.ts` are a little different from `Reflect.ts`.

By adding the `.d.ts` to `Reflect.ts`, all these issues go away. Are you considering doing this change or can I make a pull request? It should not have any negative impact on users as far as I can see.

**Comment by rolandjitsu** [comment]
Ok, my bad, I can see now that `Reflect.ts` does have some impl.
