### ISSUE TITLE
Can't Install reflect-metadata

### ISSUE THREAD

**Issue by georgeedwards** [rbuckton/ReflectDecorators#24]
I am writing a NODE stack application, which uses Angular2, passportJS and a number of other dependencies which seem to have peer dependencies on either `reflect-metadata@0.1.3` or `reflect-metadata@0.1.2`. However, whenever I install or update these, I get warnings that this dependency is not met. If I run 
>npm i reflect-metadata

then I get the following output:
```
npm i reflect-metadata --save

> bcrypt@0.8.5 install /Users/georgeedwards/Desktop/Gen-App/node_modules/bcrypt
> node-gyp rebuild

  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/bcrypt_lib.node
genapp@0.0.1 /Users/georgeedwards/Desktop/Gen-App
├── bcrypt@0.8.5  extraneous
└── UNMET PEER DEPENDENCY reflect-metadata@0.1.3

npm WARN angular2@2.0.0-beta.9 requires a peer of reflect-metadata@0.1.2 but none was installed.
```

however many times I run that command, it doesn't seem to install, or throw any errors... 

I am using a mac, running OSX 10. 

```
npm list reflect-metadata
genapp@0.0.1 /Users/georgeedwards/Desktop/Gen-App
└── UNMET PEER DEPENDENCY reflect-metadata@0.1.3

npm ERR! peer dep missing: reflect-metadata@0.1.2, required by angular2@2.0.0-beta.9
npm ERR! code 1
```

**Comment by nzager** [comment]
+1
Running Windows 10
Node v6.3.0
NPM v3.10.3
`npm i reflect-metadata
-- UNMET PEER DEPENDENCY reflect-metadata@0.1.4`

**Comment by rbuckton** [comment]
@georgeedwards It looks like angular 2.0.0-beta.9 has the specific version of 0.1.2 as a dependency for reflect-metadata. Later releases seem to have switched to using a caret version spec of ^0.1.3. If you are tied to 2.0.0-beta9 then you must use 0.1.2 specifically. If you require a later version of "reflect-metadata", consider using angular2 2.0.0-rc.2 or later.

I'm closing this as there is no action I can take. If you fill this is in error, please feel free to reopen.

**Comment by nzager** [comment]
@rbuckton thank you for your prompt response. Upon further review it appears the packages are available and functional even though the error is being thrown.
