### ISSUE TITLE
link to detailed proposal in readme is broken

### ISSUE THREAD

**Issue by JohnWhiteTB** [rbuckton/ReflectDecorators#26]
The repository readme is supposedly supposed to link to the [detailed proposal](https://github.com/jonathandturner/decorators/blob/master/specs/metadata.md), but the link is broken. As is the [Decorators](https://github.com/jonathandturner/decorators/blob/master/README.md) link pointing to the same repo.

**Comment by rbuckton** [comment]
Fixed in 4a4effe
