### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by EisenbergEffect** [rbuckton/ReflectDecorators#27]
We have people asking us what is going on with this spec. Is the TS team behind it? Is it still planned to be submitted as a proposal? Some clarification would be very welcome.

**Comment by onreachable** [comment]
I believe it still under consideration to incorporated in further versions of JavaScript, as [**rbuckton** mentioned earlier](https://github.com/rbuckton/ReflectDecorators/issues/23#issuecomment-198428761)
