### ISSUE TITLE
building ReflectDecorators with `module: amd` option

### ISSUE THREAD

**Issue by julesbou** [rbuckton/ReflectDecorators#31]
Hello there,

I'm trying to build your library as an AMD module, but without success, my command:

```
tsc --module amd
```

Result: Nothing change, with or without 'amd' option, the result is the same.

**Comment by rbuckton** [comment]
There should be no need to build this module as an AMD module as it has no imports or exports. As is, if it is loaded via AMD it will attempt to install itself into, or set itself as, the global `Reflect` object.
