### ISSUE TITLE
Loading Reflect through karma-systemjs fails to load crypto

### ISSUE THREAD

**Issue by Unitiser** [rbuckton/ReflectDecorators#32]
I'm trying to run my angular2 unit tests with karma-systemjs and I'm running into a weird issue where Reflect tries to load an undefined library called "crypto". From what I understood, Reflect makes some test to check if crypto is availlable in a node environement.

This is the line that breaks : 
`var nodeCrypto = isNode && require("crypto");`

I managed to find a quick workaround by defining a fake module in my systemjs.config, but I'm still wondering if I'm doing something wrong. Maybe there's a better way to deal with this issue. What do you think?

Here's the code for the workaround :
`exports.crypto = false;`

**Comment by rbuckton** [comment]
Fixed in f77ed03
