### ISSUE TITLE
Add support for generic type such as Array<T> when introspecting metadata

### ISSUE THREAD

**Issue by oz-frog** [rbuckton/ReflectDecorators#33]
Considering the following function declaration with a decorator added to extract metadata from a method in a typescript class.

```
@logMetadata
public getFoos(): Array<Foo> {return new Array<Foo>()};

function logMetadata(target: any, key: string) {

    var returnvalue = Reflect.getMetadata("design:returntype", target, key);
    console.log(`${key} return value: ${returnvalue.name}`);
  }

```

the statement:  ``` console.log(`${key} return value: ${returnvalue.name}`) ``` writes:

'getFoos return value: **Array**'

whereas the expected output should have been: 

'getFoos return value: **Array\<foo\>**'

Cheers

using this on ionic 2 / angular 2

**Comment by rbuckton** [comment]
TypeScript only emits type metadata for types available at run time, and does not emit type aliases, interfaces, or generics (as they do not have a JavaScript representation).

**Comment by rbuckton** [comment]
The decorator metadata emitted by TypeScript is external to this project. If you feel the ability to reason over generics at runtime is important, please feel free to open an issue on the [TypeScript](https://github.com/Microsoft/TypeScript) issue tracker.

I am closing this issue as it is external to this project. If you feel this was closed in error, please feel free to reopen with comments.
