### ISSUE TITLE
Correct way to create mutating decorator for a class constructor 

### ISSUE THREAD

**Issue by kemsky** [rbuckton/ReflectDecorators#34]
According to readme.md:
> A poorly written mutating decorator for a class constructor could cause metadata to become lost if the prototype chain is not maintained. Though, not maintaining the prototype chain in a mutating decorator for a class constructor would have other negative side effects as well. @rbuckton 

Could you please provide an example? I've encountered this while creating decorator for Angular 2.

Is metadata stored in external map using class/function as key?

**Comment by rbuckton** [comment]
Metadata is stored in a WeakMap (or a polyfill if the host does not provide an implementation) using the class as the key.

The `Reflect.getMetadata` method looks for metadata on the target as well as its prototype chain. If a class decorator were to return a new class without maintaining the prototype chain it would result in `Reflect.getMetadata` not being able to look up metadata on the prototype chain. It can also result in cases where the class prototype no longer matches the class definition itself.

There are two approaches to mutating the class constructor:

```ts
// option 1: extend class
declare class ClassLike { constructor(...args: any[]); }

function classMutator1<TClass extends Function>(target: TClass): TClass;
function classMutator1(target: typeof ClassLike): typeof ClassLike { 
    return class extends target {
        constructor(...args: any[]) { super(...args); }
    }
} 

// option 2: use function
function classMutator2<TClass extends Function>(target: TClass): TClass {
    const replacement = function (...args: any[]) {
            // ES6 (new.target not yet supported in TypeScript)
            // return Reflect.construct(target, args, this.constructor.prototype);

            // ES5
            return target.apply(this, args);
    };
    
    // ES6
    // Object.setPrototypeOf(replacement, target);
    // Object.setPrototypeOf(replacement.prototype, target.prototype);
    
    // ES5
    replacement.prototype = Object.create(target.prototype);
    replacement.prototype.constructor = replacement;
    
    return <TClass><Function>replacement;
}
```

**Comment by rbuckton** [comment]
As this is not strictly relevant to this project, I'm closing this issue.
