### ISSUE TITLE
0.1.4 drives webpack crazy

### ISSUE THREAD

**Issue by smnbbrv** [rbuckton/ReflectDecorators#38]
WARNING in ./~/reflect-metadata/Reflect.js
Critical dependencies:
841:28-35 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/reflect-metadata/Reflect.js 841:28-35

and many thigns like that after this happens.

However if I comment out the following line (841):

    return (void 0, require)("crypto");

everything is fixed.

Currently forced to roll back :(

**Comment by andreigabreanu** [comment]
Also having this issue. reverted to 0.1.3 for now.

**Comment by bentok** [comment]
Having this issue as well. Looks like there's a branch with a fix. Hopefully it gets merged soon.

**Comment by rbuckton** [comment]
Fixed in f77ed03
