### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by umasgn** [rbuckton/ReflectDecorators#39]
When i try to bundle reflect-metadata with webpack i'm getting a lot of warnings along with the following errors. should i ignore these warnings for my production build ?
![errors](https://cloud.githubusercontent.com/assets/12139440/17494846/1fb4ef36-5dd4-11e6-9256-8b87ac20f98b.png)

**Comment by witchdrash** [comment]
Downgrade to 0.1.3, 0.1.4 appears to be quite broken at the moment, at least my build just doesn't work with it because of these issues.

**Comment by umasgn** [comment]
Yes i did it. now it is working fine with some warnings but no errors.

**Comment by rbuckton** [comment]
This should be fixed in v0.1.7. Please let me know if the problem persists.
