### ISSUE TITLE
Library changes behaviour of property decorator

### ISSUE THREAD

**Issue by PFight** [rbuckton/ReflectDecorators#48]
In standard compiler implementation, return value of the property decorator is used for call of Object.defineProperty. See [example in on plunker](https://plnkr.co/edit/qizG5DjLOUiy3ydHQLVT?p=preview). 

If we include reflec-metada library, return value of the property decorator is ingnored. For example, if we include library in previus plunk, [it will break](https://plnkr.co/edit/baEz72cLHjmBDB1b5VAh?p=preview).

**Comment by rbuckton** [comment]
@PFight Can you `npm install reflect-metadata@next` to see if this change addresses your issue?

**Comment by PFight** [comment]
@rbuckton yes, in v0.1.9 it is [work good](https://plnkr.co/edit/FOuevu33wjsgB7ihEU2G?p=preview).
