### ISSUE TITLE
Would it be possible to preserve generic metadata?

### ISSUE THREAD

**Issue by snytkine** [rbuckton/ReflectDecorators#50]
Would it be possible to preserve parameterized metadata like this:

```
@mygetter
getUsers(..args): Promise<Users>

@widget
getWidget(id:number):Promise<Widget>
```

Right now design:returntype preserves return type as Promise object. It would be very helpful if somehow it preserved the type of Promise as well.

Is this something that may be implemented in the future? This would be very helpful for libraries that auto-generate documentation and also to generate schema from class definition.

**Comment by rbuckton** [comment]
It would be better to post this question/issue on the http://github.com/Microsoft/TypeScript repository as design-time metadata is a TypeScript-specific feature.
